{% set name = "base-node-rpc" %}
{% set version = "0.36" %}
{% set github_user = "sci-bots" %}
{% set license = "MIT" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/{{ github_user }}/{{ name }}
  git_rev: v{{ version }}

requirements:
  build:
    - arduino-rpc >=1.10
    - future
    # .. versionadded:: 0.30
    - nadamq >=0.13
    - paver
    - pip
    - platformio-framework-arduinoavr
    - platformio-framework-arduinoteensy
    - platformio-helpers >=0.4
    - platformio-tool-avrdude
    - platformio-tool-scons
    - platformio-tool-teensy
    - platformio-toolchain-atmelavr
    - platformio-toolchain-gccarmnoneeabi
    - python 2.7*
    - serial-device >=0.8

  run:
    - arduino-rpc >=1.10
    # .. versionadded:: 0.30
    - nadamq >=0.13
    - python 2.7*
    - platformio-helpers >=0.4
    - platformio-tool-avrdude
    - platformio-tool-scons
    - platformio-tool-teensy
    - serial-device >=0.8

about:
  home: https://github.com/{{ github_user }}/{{ name }}
  license: {{ license }}
